#!/usr/bin/env bash

#
# Copyright 2022 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set -eou pipefail

# Ensure script runs in correct directory
cd $(dirname $0)

# Load common setup
source ./.util/common.sh

parse_args $*

# Switch to windows script
if [[ "$MACHINE" = "Windows" ]]; then
    exec ./setup.bat $($ARG_RESET && echo -Reset)
fi

find_python_version

# Run setup

if $ARG_RESET; then
    echo -e "${BLUE}Recreating virtual environment${NC}..."
    $PY -m venv --copies --clear --upgrade-deps $ENVIRONMENT_PATH
elif [[ -d "$ENVIRONMENT_PATH" ]];then
    echo -e "${BLUE}Updating virtual environment${NC}..."
    $PY -m venv --copies --upgrade --upgrade-deps $ENVIRONMENT_PATH
else
    echo -e "${BLUE}Creating virtual environment${NC}..."
    $PY -m venv --copies --upgrade-deps $ENVIRONMENT_PATH
fi

activate_environment

echo -e "${BLUE}Running basic installation${NC}..."
.util/setup.sh

# Store Checksums for update warning
write_checksums

echo -e "${BLUE}Done${NC}"
